<?php

return [
    'admin_access_control'                    => false,
    'admin_export_only'                       => false,
    'cache_dir'                               => 'storage/cache/',
    'calculate_response_time'                 => false,
    'calendar'                                => [
        'default_view'              => 'week',
        'show_calls_by_default'     => true,
        'show_tasks_by_default'     => true,
        'show_completed_by_default' => true,
        'editview_width'            => 990,
        'editview_height'           => 485,
        'day_timestep'              => 15,
        'week_timestep'             => 30,
        'items_draggable'           => true,
        'items_resizable'           => true,
        'enable_repeat'             => true,
        'max_repeat_count'          => 1000,
    ],
    'chartEngine'                             => 'Jit',
    'common_ml_dir'                           => '',
    'create_default_user'                     => false,
    'currency'                                => '',
    'dashlet_auto_refresh_min'                => '30',
    'dashlet_display_row_options'             => ['1', '3', '5', '10'],
    'date_formats'                            => [
        'Y-m-d' => '2010-12-23',
        'm-d-Y' => '12-23-2010',
        'd-m-Y' => '23-12-2010',
        'Y/m/d' => '2010/12/23',
        'm/d/Y' => '12/23/2010',
        'd/m/Y' => '23/12/2010',
        'Y.m.d' => '2010.12.23',
        'd.m.Y' => '23.12.2010',
        'm.d.Y' => '12.23.2010',
    ],
    'datef'                                   => 'm/d/Y',
    'dbconfig'                                => [
        'db_host_name'     => env('DB_HOST', 'localhost'),
        'db_host_instance' => 'SQLEXPRESS',
        'db_user_name'     => env('DB_USERNAME', 'forge'),
        'db_password'      => env('DB_PASSWORD', ''),
        'db_name'          => env('DB_DATABASE', 'forge'),
        'db_type'          => env('DB_TYPE', ''),
        'db_port'          => env('DB_PORT', ''),
        'db_manager'       => env('DB_MANAGER', 'MysqliManager'),
    ],
    'dbconfigoption'                          => [
        'persistent' => true,
        'autofree'   => false,
        'debug'      => 0,
        'ssl'        => false,
        'collation'  => 'utf8_general_ci',
    ],
    'default_action'                          => 'index',
    'default_charset'                         => 'UTF-8',
    'default_currencies'                      => [
        'AUD' => [
            'name'    => 'Australian Dollars',
            'iso4217' => 'AUD',
            'symbol'  => '$',
        ],
        'BRL' => [
            'name'    => 'Brazilian Reais',
            'iso4217' => 'BRL',
            'symbol'  => 'R$',
        ],
        'GBP' => [
            'name'    => 'British Pounds',
            'iso4217' => 'GBP',
            'symbol'  => '£',
        ],
        'CAD' => [
            'name'    => 'Canadian Dollars',
            'iso4217' => 'CAD',
            'symbol'  => '$',
        ],
        'CNY' => [
            'name'    => 'Chinese Yuan',
            'iso4217' => 'CNY',
            'symbol'  => '￥',
        ],
        'EUR' => [
            'name'    => 'Euro',
            'iso4217' => 'EUR',
            'symbol'  => '€',
        ],
        'HKD' => [
            'name'    => 'Hong Kong Dollars',
            'iso4217' => 'HKD',
            'symbol'  => '$',
        ],
        'INR' => [
            'name'    => 'Indian Rupees',
            'iso4217' => 'INR',
            'symbol'  => '₨',
        ],
        'KRW' => [
            'name'    => 'Korean Won',
            'iso4217' => 'KRW',
            'symbol'  => '₩',
        ],
        'YEN' => [
            'name'    => 'Japanese Yen',
            'iso4217' => 'JPY',
            'symbol'  => '¥',
        ],
        'MXM' => [
            'name'    => 'Mexican Pesos',
            'iso4217' => 'MXM',
            'symbol'  => '$',
        ],
        'SGD' => [
            'name'    => 'Singaporean Dollars',
            'iso4217' => 'SGD',
            'symbol'  => '$',
        ],
        'CHF' => [
            'name'    => 'Swiss Franc',
            'iso4217' => 'CHF',
            'symbol'  => 'SFr.',
        ],
        'THB' => [
            'name'    => 'Thai Baht',
            'iso4217' => 'THB',
            'symbol'  => '฿',
        ],
        'USD' => [
            'name'    => 'US Dollars',
            'iso4217' => 'USD',
            'symbol'  => '$',
        ],
    ],
    'default_currency_iso4217'                => 'USD',
    'default_currency_name'                   => 'US Dollars',
    'default_currency_significant_digits'     => 2,
    'default_currency_symbol'                 => '$',
    'default_date_format'                     => 'm/d/Y',
    'default_decimal_seperator'               => '.',
    'default_email_charset'                   => 'UTF-8',
    'default_email_client'                    => 'sugar',
    'default_email_editor'                    => 'html',
    'default_export_charset'                  => 'UTF-8',
    'default_language'                        => 'en_us',
    'default_locale_name_format'              => 's f l',
    'default_max_tabs'                        => '7',
    'default_module'                          => 'Home',
    'default_navigation_paradigm'             => 'gm',
    'default_number_grouping_seperator'       => ',',
    'default_password'                        => '',
    'default_permissions'                     => [
        'dir_mode'  => 1528,
        'file_mode' => 432,
        'user'      => '',
        'group'     => '',
    ],
    'default_subpanel_links'                  => false,
    'default_subpanel_tabs'                   => true,
    'default_swap_last_viewed'                => false,
    'default_swap_shortcuts'                  => false,
    'default_theme'                           => 'Sugar',
    'default_time_format'                     => 'H:i',
    'default_user_is_admin'                   => false,
    'default_user_name'                       => '',
    'demoData'                                => 'no',
    'developerMode'                           => env('APP_DEVELOPER', false),
    'debug'                                   => env('APP_DEBUG', false),
    'disable_export'                          => false,
    'disable_persistent_connections'          => 'false',
    'display_email_template_variable_chooser' => false,
    'display_inbound_email_buttons'           => false,
    'dump_slow_queries'                       => false,
    'email_default_client'                    => 'sugar',
    'email_default_delete_attachments'        => true,
    'email_default_editor'                    => 'html',
    'email_xss'                               => 'YToxMzp7czo2OiJhcHBsZXQiO3M6NjoiYXBwbGV0IjtzOjQ6ImJhc2UiO3M6NDoiYmFzZSI7czo1OiJlbWJlZCI7czo1OiJlbWJlZCI7czo0OiJmb3JtIjtzOjQ6ImZvcm0iO3M6NToiZnJhbWUiO3M6NToiZnJhbWUiO3M6ODoiZnJhbWVzZXQiO3M6ODoiZnJhbWVzZXQiO3M6NjoiaWZyYW1lIjtzOjY6ImlmcmFtZSI7czo2OiJpbXBvcnQiO3M6ODoiXD9pbXBvcnQiO3M6NToibGF5ZXIiO3M6NToibGF5ZXIiO3M6NDoibGluayI7czo0OiJsaW5rIjtzOjY6Im9iamVjdCI7czo2OiJvYmplY3QiO3M6MzoieG1wIjtzOjM6InhtcCI7czo2OiJzY3JpcHQiO3M6Njoic2NyaXB0Ijt9',
    'export_delimiter'                        => ',',
    'history_max_viewed'                      => 50,
    'host_name'                               => env('APP_HOST', 'localhost'),
    'import_dir'                              => storage_path('import'.DIRECTORY_SEPARATOR),
    'import_max_execution_time'               => 3600,
    'import_max_records_per_file'             => 100,
    'import_max_records_total_limit'          => '',
    'inbound_email_case_subject_macro'        => '[%1]',
    'installer_locked'                        => true,
    'jobs'                                    => [
        'min_retry_interval' => 30,
        'max_retries'        => 5,
        'timeout'            => 86400,
    ],
    'js_custom_version'                       => '',
    'js_lang_version'                         => 1,
    'languages'                               => [
        'en_us' => 'English (US)',
    ],
    'large_scale_test'                        => false,
    'lead_conv_activity_opt'                  => 'donothing',
    'list_max_entries_per_page'               => 20,
    'list_max_entries_per_subpanel'           => '50',
    'lock_default_user_name'                  => false,
    'lock_homepage'                           => false,
    'lock_subpanels'                          => false,
    'log_dir'                                 => storage_path('logs'.DIRECTORY_SEPARATOR),
    'log_memory_usage'                        => false,
    'name_formats'                            => [
        's f l'  => 's f l',
        'f l'    => 'f l',
        's l'    => 's l',
        'l, s f' => 'l, s f',
        'l, f'   => 'l, f',
        's l, f' => 's l, f',
        'l s f'  => 'l s f',
        'l f s'  => 'l f s',
    ],
    'passwordsetting'                         => [
        'SystemGeneratedPasswordON' => true,
        'generatepasswordtmpl'      => 'a34c7050-ea46-929e-c835-569acc42662a',
        'lostpasswordtmpl'          => 'af26ec8f-e6c6-1d42-78ee-569acc03d00b',
        'forgotpasswordON'          => true,
        'linkexpiration'            => true,
        'linkexpirationtime'        => 24,
        'linkexpirationtype'        => 60,
        'systexpiration'            => 1,
        'systexpirationtime'        => 7,
        'systexpirationtype'        => '0',
        'systexpirationlogin'       => '',
        'minpwdlength'              => 6,
        'oneupper'                  => true,
        'onelower'                  => true,
        'onenumber'                 => true,
    ],
    'portal_view'                             => 'single_user',
    'require_accounts'                        => true,
    'resource_management'                     => [
        'special_query_limit'   => 50000,
        'special_query_modules' => [
            0 => 'Reports',
            1 => 'Export',
            2 => 'Import',
            3 => 'Administration',
            4 => 'Sync',
        ],
        'default_limit'         => 1000,
    ],
    'rss_cache_time'                          => '10800',
    'save_query'                              => 'all',
    'search_wildcard_char'                    => '%',
    'search_wildcard_infront'                 => false,
    'session_dir'                             => '',
    'showDetailData'                          => true,
    'showThemePicker'                         => true,
    'site_url'                                => env('APP_URL', 'http://localhost'),
    'slow_query_time_msec'                    => '100',
    'sugar_version'                           => '6.5.22',
    'sugarbeet'                               => true,
    'time_formats'                            => [
        'H:i'   => '23:00',
        'h:ia'  => '11:00pm',
        'h:iA'  => '11:00PM',
        'h:i a' => '11:00 pm',
        'h:i A' => '11:00 PM',
        'H.i'   => '23.00',
        'h.ia'  => '11.00pm',
        'h.iA'  => '11.00PM',
        'h.i a' => '11.00 pm',
        'h.i A' => '11.00 PM',
    ],
    'timef'                                   => 'H:i',
    'tmp_dir'                                 => storage_path('tmp'.DIRECTORY_SEPARATOR),
    'tracker_max_display_length'              => 30,
    'translation_string_prefix'               => false,
    'unique_key'                              => '8c4daba37aa40e895a2ff4a285110a58',
    'upload_badext'                           => [
        'php',
        'php3',
        'php4',
        'php5',
        'pl',
        'cgi',
        'py',
        'asp',
        'cfm',
        'js',
        'vbs',
        'html',
        'htm',
    ],
    'upload_dir'                              => base_path('upload'.DIRECTORY_SEPARATOR),
    'upload_maxsize'                          => 3000000,
    'use_common_ml_dir'                       => false,
    'use_real_names'                          => true,
    'vcal_time'                               => '2',
    'verify_client_ip'                        => true,
];